### ISSUE TITLE
Allow comments in code

### ISSUE THREAD

**Issue by nextstopsun** [sputnik-maps/mvt-styler#4]
When commenting out lines of code the internal linter thinks it's an error. Quite inconvenient:)

**Comment by orofarne** [comment]
Style is a JSON. JSON is not allows comments. Sorry.

**Comment by nextstopsun** [comment]
Ясненько:) У себя я обходил это, просто сделав стиль объектом Javascript. Комменты очень помогают при экспериментах со стилем:)

**Comment by orofarne** [comment]
Да, но со стилем может работать не только JS-код.
